############################################################
## 生产环境下的挂载配置文件
#############################################################
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&useUnicode=true&autoReconnect=true
    username: root
    password: 123456